# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

#env:
#  GIST_ID: 9338f65b1df98fef0aa32aabb03296cf
#  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.20.x','1.21.x','1.22.x','1.23.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: go test -race -covermode atomic -coverprofile=profile.cov ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go-version }}
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true