# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

env:
  GIST_ID: 9338f65b1df98fef0aa32aabb03296cf
  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20.x','1.21.x','1.22.x','1.23.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -o test.out

    - name: Coverage
      run: go tool cover -func cover.out > cover.out

    - name: CI Badges
      uses: gaelgirodon/ci-badges-action@v1.7.0
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      with:
        gist-id: ${{ env.GIST_ID }}
        token: ${{ env.GIST_TOKEN }}
        #prefix: ringbuffer
        ref: false